blueprint:
  name: STYRBAR (Z2M) – Farben cyclen + On/Off + Hold-Dimmen
  description: >
    IKEA STYRBAR über Zigbee2MQTT action-topic:
    - on/off
    - arrow_left/right_click: Farben cyclen
    - brightness_move_up/down: Hold dimmen
    - brightness_stop: stop
    Farben kommen als mehrzeiliger Text, je Zeile: R,G,B
  domain: automation

  input:
    z2m_topic:
      name: Zigbee2MQTT Action Topic
      description: z.B. zigbee2mqtt/Schalter Marlene/action
      selector:
        text: {}

    target_light:
      name: Ziel-Lampe
      selector:
        entity:
          domain: light

    color_index_helper:
      name: Farbindex (input_number)
      description: Min 0, Max 9, Schritt 1
      selector:
        entity:
          domain: input_number

    dim_active_helper:
      name: Dimmen aktiv (input_boolean)
      selector:
        entity:
          domain: input_boolean

    color_count:
      name: Anzahl Farben (1–10)
      default: 8
      selector:
        number:
          min: 1
          max: 10
          step: 1
          mode: slider

    colors_text:
      name: Farben (je Zeile R,G,B)
      description: >
        Beispiel:
        255,0,0
        0,255,0
        0,0,255
      default: |
        255,0,0
        255,128,0
        255,255,0
        0,255,0
        0,255,255
        0,0,255
        128,0,255
        255,0,128
      selector:
        text:
          multiline: true

    start_brightness:
      name: Starthelligkeit (%)
      default: 80
      selector:
        number:
          min: 1
          max: 100
          step: 1
          mode: slider

    dim_step_pct:
      name: Dimm-Schritt (%)
      default: 4
      selector:
        number:
          min: 1
          max: 20
          step: 1
          mode: slider

    dim_tick_ms:
      name: Dimm-Intervall (ms)
      default: 150
      selector:
        number:
          min: 80
          max: 500
          step: 10
          mode: slider

mode: restart
max_exceeded: silent

trigger:
  - platform: mqtt
    topic: !input z2m_topic
    payload: "on"
    id: "btn_on"

  - platform: mqtt
    topic: !input z2m_topic
    payload: "off"
    id: "btn_off"

  - platform: mqtt
    topic: !input z2m_topic
    payload: "arrow_left_click"
    id: "left"

  - platform: mqtt
    topic: !input z2m_topic
    payload: "arrow_right_click"
    id: "right"

  - platform: mqtt
    topic: !input z2m_topic
    payload: "brightness_move_up"
    id: "dim_up"

  - platform: mqtt
    topic: !input z2m_topic
    payload: "brightness_move_down"
    id: "dim_down"

  - platform: mqtt
    topic: !input z2m_topic
    payload: "brightness_stop"
    id: "dim_stop"

variables:
  light_entity: !input target_light
  idx_entity: !input color_index_helper
  dim_active: !input dim_active_helper
  count: !input color_count
  colors_text: !input colors_text
  brightness: !input start_brightness
  step: !input dim_step_pct
  tick: !input dim_tick_ms

action:
  - variables:
      parsed_colors: >
        {% set ns = namespace(colors=[]) %}
        {% for line in colors_text.splitlines() %}
          {% set l = line | trim %}
          {% if l %}
            {% set parts = l.split(',') %}
            {% if parts | length == 3 %}
              {% set rgb = parts | map('int') | list %}
              {% if rgb[0] is number and rgb[1] is number and rgb[2] is number %}
                {% set ns.colors = ns.colors + [rgb] %}
              {% endif %}
            {% endif %}
          {% endif %}
        {% endfor %}
        {{ ns.colors }}
      n: >
        {% set l = parsed_colors | length %}
        {% set c = count | int(1) %}
        {{ [l, c] | min if l > 0 else 1 }}
      colors: "{{ parsed_colors[:(n | int(1))] }}"
      current: "{{ states(idx_entity) | int(0) }}"
      idx: "{{ current if 0 <= current < (n | int(1)) else 0 }}"

  # Bei allen Nicht-Dimm-Aktionen Dimmen beenden (damit nichts „hängen bleibt“)
  - choose:
      - conditions: "{{ trigger.id in ['btn_on','btn_off','left','right'] }}"
        sequence:
          - service: input_boolean.turn_off
            target:
              entity_id: "{{ dim_active }}"

  - choose:

      - conditions: "{{ trigger.id == 'btn_off' }}"
        sequence:
          - service: light.turn_off
            target:
              entity_id: "{{ light_entity }}"

      - conditions: "{{ trigger.id == 'btn_on' }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ light_entity }}"
            data:
              rgb_color: "{{ colors[idx] }}"
              brightness_pct: "{{ brightness }}"

      - conditions: "{{ trigger.id == 'left' }}"
        sequence:
          - variables:
              new: "{{ (idx + 1) % (n | int(1)) }}"
          - service: input_number.set_value
            target:
              entity_id: "{{ idx_entity }}"
            data:
              value: "{{ new }}"
          - service: light.turn_on
            target:
              entity_id: "{{ light_entity }}"
            data:
              rgb_color: "{{ colors[new] }}"
              brightness_pct: "{{ brightness }}"

      - conditions: "{{ trigger.id == 'right' }}"
        sequence:
          - variables:
              new: "{{ (idx - 1) % (n | int(1)) }}"
          - service: input_number.set_value
            target:
              entity_id: "{{ idx_entity }}"
            data:
              value: "{{ new }}"
          - service: light.turn_on
            target:
              entity_id: "{{ light_entity }}"
            data:
              rgb_color: "{{ colors[new] }}"
              brightness_pct: "{{ brightness }}"

      - conditions: "{{ trigger.id == 'dim_up' }}"
        sequence:
          - service: input_boolean.turn_on
            target:
              entity_id: "{{ dim_active }}"
          - repeat:
              while:
                - condition: state
                  entity_id: "{{ dim_active }}"
                  state: "on"
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: "{{ light_entity }}"
                  data:
                    brightness_step_pct: "{{ step }}"
                - delay:
                    milliseconds: "{{ tick }}"

      - conditions: "{{ trigger.id == 'dim_down' }}"
        sequence:
          - service: input_boolean.turn_on
            target:
              entity_id: "{{ dim_active }}"
          - repeat:
              while:
                - condition: state
                  entity_id: "{{ dim_active }}"
                  state: "on"
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: "{{ light_entity }}"
                  data:
                    brightness_step_pct: "{{ -step }}"
                - delay:
                    milliseconds: "{{ tick }}"

      - conditions: "{{ trigger.id == 'dim_stop' }}"
        sequence:
          - service: input_boolean.turn_off
            target:
              entity_id: "{{ dim_active }}"
